[book]
title = "Quoracle"
authors = ["Greg Burd"]
description = "Construct, analyze, and optimize read-write quorum systems in Rust"
language = "en"
src = "docs/src"

[build]
build-dir = "docs/book"

[output.html]
git-repository-url = "https://codeberg.org/gregburd/rs-quoracle"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://codeberg.org/gregburd/rs-quoracle/_edit/main/{path}"
site-url = "/rs-quoracle/"

[output.html.fold]
enable = true
level = 0
